### ISSUE TITLE
While converting WideResnet I get an Error Unsupported ONNX ops of type: Shape,Squeeze,Unsqueeze

### ISSUE THREAD

**Issue by setuc** [onnx/onnx-coreml#325]
I am currently using it in Python 2.7 and I installed coreml via pip. Would you want a copy of the code?

**Comment by aseemw** [comment]
Yes it would be great if you give directions to generate the .onnx file that causes these errors.

**Comment by pavan4** [comment]
Any update to support the Squeeze, Unsqueeze, Shape, Tile ops?

**Comment by pavan4** [comment]
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.nn.init as init
from torch.autograd import Variable
from torch import Tensor
import numpy as np

a = Tensor(np.zeros((64,256,320,2)))

def get_trainable_number(variable):
    num = 1
    shape = list(variable.shape)
    for i in shape:
        num *= i
    return num

class testNet(nn.Module):
    def __init__(self):
        super(testNet, self).__init__()
        
        total_num = 0
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                init.kaiming_normal(m.weight, mode='fan_out')
                total_num += get_trainable_number(m.weight)
                if m.bias is not None:
                    init.constant(m.bias, 0)
                    total_num += get_trainable_number(m.bias)
            elif isinstance(m, nn.BatchNorm2d):
                init.constant(m.weight, 1)
                total_num += get_trainable_number(m.weight)
                init.constant(m.bias, 0)
                total_num += get_trainable_number(m.bias)
            elif isinstance(m, nn.Linear):
                init.normal(m.weight, std=1e-3)
                total_num += get_trainable_number(m.weight)
                if m.bias is not None:
                    init.constant(m.bias, 0)
                    total_num += get_trainable_number(m.bias)
    def forward(self, a):
        #a = a.squeeze(0)
        nn.Sequential()
        a = a.unsqueeze(0)
        
        return [a]
        
testnet = testNet()
testnet.eval()
torch.onnx.export(testnet,(a) , 'test.onnx', verbose=True, input_names=['ip'], output_names=['op'] )

     
```


import onnx

```
model = onnx.load('test.onnx')
from onnx_coreml import convert
coreml_model = convert(
    model
)
coreml_model.save('testnet.mlmodel')
```

The above produces the error ` NotImplementedError: Unsupported ONNX ops of type: Unsqueeze` 

The onnx file is attached here for the above network.
[test.onnx.zip](https://github.com/onnx/onnx-coreml/files/2314920/test.onnx.zip)

**Comment by aseemw** [comment]
Thank you for the code. There were some changes in opset version 7 which cause this error. 
I'll take a look. A few fixes have been put up in PR #328 which might solve the unsqueeze issue.

**Comment by pavan4** [comment]
@aseemw  Thanks.

Is there any way to give some sample code for writing up these custom layers ? 

In WWDC'18 presentation there, a demo for gridsampling was shown. However, the code for computing the output is not in the presentation nor an example is linked outside anywhere. Anyway to get a sample for the grid sampling as well? 

We basically have a network using [torch grid sample](https://pytorch.org/docs/stable/nn.html#torch.nn.functional.grid_sample) and having a tough time getting it into coreml essentially.

**Comment by aseemw** [comment]
Hi have you tried with the latest master (building from source). 

I'll look into it. It would be useful if you can also share a simple model code that demonstrates the issue. 

The new pytorch add these additional layers in the ONNX format which is causing the converter to break.

**Comment by leonardoaraujosantos** [comment]
I tried the following code and works if I calculate by hand the view(Pytorch reshape) parameters.
But it will break the onyx-->coreml conversion if I use (x = x.view(x.size()[0], -1))
```python
import torch
import torch.nn as nn
from torch.autograd import Variable
import torch.onnx as torch_onnx
from onnx_coreml import convert

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=(3,3), stride=1, padding=0, bias=True)

    def forward(self, inputs):
        x = self.conv(inputs)
        # The view create the reshape/unsqueeze issue when exporting to coreml
        #x = x.view(x.size()[0], -1)
        x = x.view(1, 307328)
        print(x.size())
        return x

# Use this an input trace to serialize the model
input_shape = (3, 100, 100)
model_onnx_path = "torch_model.onnx"
model = Model()
model.train(False)

# Export the model to an ONNX file
dummy_input = torch.randn(1, *input_shape)
output = torch_onnx.export(model, 
                          dummy_input, 
                          model_onnx_path, 
                          export_params=True,
                          verbose=True)

# Export to coreml
coreml_model = convert('./torch_model.onnx')
coreml_model.save('./test.mlmodel')
```

So I calculated all the view parameters on my bigger models, but I also have the following issue
```bash
ValueError: Missing initializer error in op of type MatMul, with input name = 1, output name = 158. Error message: Weight tensor: 157 not found in the graph initializer
```

**Comment by leonardoaraujosantos** [comment]
I've reported this issue on Pytorch repository, and they are state that those ops are valid on ONNX
https://github.com/pytorch/pytorch/issues/11670

**Comment by aseemw** [comment]
PR #336 should fix this issue.

**Comment by jalola** [comment]
Hi,

I just pulled the master branch but I still get this error when converting resnet50 to coreml from onnx
`NotImplementedError: Unsupported ONNX ops of type: Unsqueeze,Squeeze
 `

I am using Pytorch 0.4.1, I didn't try 0.4.0 version yet.

**Comment by aseemw** [comment]
Which version of resnet50 is that? 

The following code works with the master branch: 

```
import torch
from torchvision import models
import onnx
from onnx_coreml import convert

# Load model
model = models.resnet50(pretrained=True)
content_image = torch.randn((1, 3, 224, 224))
output = torch.onnx.export(model, content_image, "/tmp/torchvision_imagenet.onnx")

onnx_model = onnx.load("/tmp/torchvision_imagenet.onnx")
coreml_model = convert(onnx_model)
```

**Comment by jalola** [comment]
I forgot the Flatten layer code:

```
class Flatten(nn.Module):
    def __init__(self): super().__init__()
    def forward(self, x): return x.view(x.size(0), -1)
```

**Comment by aseemw** [comment]
I'll take a look.

**Comment by aseemw** [comment]
@jalola can you check if adding the following in "onnx-coreml/_operators.py" works?

add [here](https://github.com/onnx/onnx-coreml/blob/bd6586483e68e346cf1ef9abcccb57c50ee91d6b/onnx_coreml/_operators.py#L1052):

```
...
"Unsqueeze": _convert_identity,
"Squeeze": _convert_identity
}
```

add the function:
```
def _convert_identity(builder, node, graph, err):
    builder.add_activation(
        name=node.name,
        non_linearity = 'LINEAR',
        input_name=node.inputs[0],
        output_name=node.outputs[0],
        params=[1.0, 0.0]
   )
```

**Comment by jalola** [comment]
@aseemw 
I added above code and it works. No more error.

Thanks for the fix.
