### ISSUE TITLE
CoreML only supports Reshape layer when the target shape is static and known apriori

### ISSUE THREAD

**Issue by h-shib** [onnx/onnx-coreml#347]
When I convert onnx model to mlmodel, I got the error below.

**error message**
```
Traceback (most recent call last):
  File "onnx_to_coreml.py", line 15, in <module>
    deprocessing_args={'image_scale': 255})
  File "/foo/lib/python3.6/site-packages/onnx_coreml/converter.py", line 458, in convert
    _convert_node(builder, node, graph, err)
  File "/foo/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1755, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/foo/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 443, in _convert_reshape
    "CoreML only supports Reshape layer when the target shape is static and known apriori")
  File "/foo/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 71, in missing_initializer
    format(node.op_type, node.inputs[0], node.outputs[0], err_message)
ValueError: Missing initializer error in op of type Reshape, with input name = 40, output name = 68. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori
```

**environment**
```
onnx==1.3.0
onnx-coreml==0.3.0
```

I couldn't understand what the error message says.  
Doesn't `onnx-coreml` support `Reshape` function? What should I do to fix this error?

This is model graph.
```
graph torch-jit-export (
  %input_image[FLOAT, 1x3x100x100]
) initializers (
  %learned_0[FLOAT, 56x3x5x5]
  %learned_1[FLOAT, 56]
  %learned_2[FLOAT, 1]
  %learned_3[FLOAT, 12x56x1x1]
  %learned_4[FLOAT, 12]
  %learned_5[FLOAT, 1]
  %learned_6[FLOAT, 12x12x3x3]
  %learned_7[FLOAT, 12]
  %learned_8[FLOAT, 1]
  %learned_9[FLOAT, 12x12x3x3]
  %learned_10[FLOAT, 12]
  %learned_11[FLOAT, 1]
  %learned_12[FLOAT, 12x12x3x3]
  %learned_13[FLOAT, 12]
  %learned_14[FLOAT, 1]
  %learned_15[FLOAT, 12x12x3x3]
  %learned_16[FLOAT, 12]
  %learned_17[FLOAT, 1]
  %learned_18[FLOAT, 12x12x1x1]
  %learned_19[FLOAT, 12]
  %learned_20[FLOAT, 1]
) {
  %22 = Pad[mode = 'reflect', pads = [0, 0, 2, 2, 0, 0, 2, 2]](%input_image)
  %23 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]](%22, %learned_0, %learned_1)
  %24 = PRelu(%23, %learned_2)
  %25 = Conv[dilations = [1, 1], group = 1, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]](%24, %learned_3, %learned_4)
  %26 = PRelu(%25, %learned_5)
  %27 = Pad[mode = 'reflect', pads = [0, 0, 1, 1, 0, 0, 1, 1]](%26)
  %28 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [0, 0, 0, 0], strides = [1, 1]](%27, %learned_6, %learned_7)
  %29 = PRelu(%28, %learned_8)
  %30 = Pad[mode = 'reflect', pads = [0, 0, 1, 1, 0, 0, 1, 1]](%29)
  %31 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [0, 0, 0, 0], strides = [1, 1]](%30, %learned_9, %learned_10)
  %32 = PRelu(%31, %learned_11)
  %33 = Pad[mode = 'reflect', pads = [0, 0, 1, 1, 0, 0, 1, 1]](%32)
  %34 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [0, 0, 0, 0], strides = [1, 1]](%33, %learned_12, %learned_13)
  %35 = PRelu(%34, %learned_14)
  %36 = Pad[mode = 'reflect', pads = [0, 0, 1, 1, 0, 0, 1, 1]](%35)
  %37 = Conv[dilations = [1, 1], group = 1, kernel_shape = [3, 3], pads = [0, 0, 0, 0], strides = [1, 1]](%36, %learned_15, %learned_16)
  %38 = PRelu(%37, %learned_17)
  %39 = Conv[dilations = [1, 1], group = 1, kernel_shape = [1, 1], pads = [0, 0, 0, 0], strides = [1, 1]](%38, %learned_18, %learned_19)
  %40 = PRelu(%39, %learned_20)
  %41 = Shape(%40)
  %42 = Slice[axes = [0], ends = [1], starts = [0]](%41)
  %43 = Squeeze[axes = [0]](%42)
  %44 = Shape(%40)
  %45 = Slice[axes = [0], ends = [2], starts = [1]](%44)
  %46 = Squeeze[axes = [0]](%45)
  %47 = Shape(%40)
  %48 = Slice[axes = [0], ends = [3], starts = [2]](%47)
  %49 = Squeeze[axes = [0]](%48)
  %50 = Shape(%40)
  %51 = Slice[axes = [0], ends = [4], starts = [3]](%50)
  %52 = Squeeze[axes = [0]](%51)
  %53 = Constant[value = <Scalar Tensor []>]()
  %54 = Div[broadcast = 1](%46, %53)
  %55 = Constant[value = <Scalar Tensor []>]()
  %56 = Mul[broadcast = 1](%49, %55)
  %57 = Constant[value = <Scalar Tensor []>]()
  %58 = Mul[broadcast = 1](%52, %57)
  %59 = Constant[value = <Scalar Tensor []>]()
  %60 = Constant[value = <Scalar Tensor []>]()
  %61 = Unsqueeze[axes = [0]](%43)
  %62 = Unsqueeze[axes = [0]](%54)
  %63 = Unsqueeze[axes = [0]](%59)
  %64 = Unsqueeze[axes = [0]](%60)
  %65 = Unsqueeze[axes = [0]](%49)
  %66 = Unsqueeze[axes = [0]](%52)
  %67 = Concat[axis = 0](%61, %62, %63, %64, %65, %66)
  %68 = Reshape(%40, %67)
  %69 = Transpose[perm = [0, 1, 4, 2, 5, 3]](%68)
  %70 = Unsqueeze[axes = [0]](%43)
  %71 = Unsqueeze[axes = [0]](%54)
  %72 = Unsqueeze[axes = [0]](%56)
  %73 = Unsqueeze[axes = [0]](%58)
  %74 = Concat[axis = 0](%70, %71, %72, %73)
  %output_image = Reshape(%69, %74)
  return %output_image
}
```

**Comment by aseemw** [comment]
What the error message means is that CoreML supports static reshape operation but not dynamic reshape. 
That is, if the shape input can be fully determined at compile time, it can be converted, but if it can be only determined at runtime (which means its dynamic, non static) then it cannot be converted to CoreML.

Having said that, in most cases shape tends to be a static parameter.
It seems in this graph, there is a sub-graph that evaluates the shape parameter, which is static and can be evaluated prior to conversion. I suspect we could add an optimization step to the converter to do that first. 
If you can share the .onnx file it would be great, I can take a look at it.

**Comment by h-shib** [comment]
Here is the onnx file.  
https://www.dropbox.com/s/or80nq47264vzmp/tmp.onnx?dl=0

**Comment by aseemw** [comment]
I added an optimization in PR #348. I think that should solve this particular issue. Please give it a try.

**Comment by h-shib** [comment]
It worked! Thank you so much!

**Comment by alexanderhudym** [comment]
@aseemw Problem is not resolved. 
Missing initializer error in op of type Reshape, with input name = 94, output name = 104. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori

**Comment by dzyjjpy** [comment]
@alexanderhudym do you sovle the issue? I met the same information when converting YOLACT for segmentation task.

@aseemw I install onnx-coreml 1.2 by source code way(./install.sh), it dosen't work. do you have any suggestion for it?

226/308: Converting Node Type Gather
227/308: Converting Node Type Unsqueeze
228/308: Converting Node Type Concat
229/308: Converting Node Type Reshape
Traceback (most recent call last):
  File "/home/jiapy/workspace/segmentation/yolact-coreml/onnx_to_coreml.py", line 15, in <module>
    minimum_ios_deployment_target='12'    # TypeError: 'set' object is not callable
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/converter.py", line 630, in convert
    _convert_node(builder, node, graph, err)
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1985, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 522, in _convert_reshape
    "CoreML only supports Reshape layer when the target shape is static and known apriori")
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 75, in missing_initializer
    format(node.op_type, node.inputs[0], node.outputs[0], err_message, self.rerun_suggestion)
**ValueError: Missing initializer error in op of type Reshape, with input name = 586, output name = 596. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori** 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.


Process finished with exit code 1

```
import sys
from onnx import onnx_pb
from onnx_coreml import convert

model_in = sys.argv[1]
model_out = sys.argv[2]

model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
coreml_model = convert(model_proto,
					   None,
                       image_input_names=['image'],
					   add_custom_layers=True,
					   minimum_ios_deployment_target='12'    # TypeError: 'set' object is not callable
                      )
coreml_model.save(model_out)
```

**Comment by dzyjjpy** [comment]
@alexanderhudym do you sovle the issue? I met the same information when converting YOLACT for segmentation task.

@aseemw I install onnx-coreml 1.2 by source code way(./install.sh), it dosen't work. do you have any suggestion for it?

226/308: Converting Node Type Gather
227/308: Converting Node Type Unsqueeze
228/308: Converting Node Type Concat
229/308: Converting Node Type Reshape
Traceback (most recent call last):
  File "/home/jiapy/workspace/segmentation/yolact-coreml/onnx_to_coreml.py", line 15, in <module>
    minimum_ios_deployment_target='12'    # TypeError: 'set' object is not callable
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/converter.py", line 630, in convert
    _convert_node(builder, node, graph, err)
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 1985, in _convert_node
    return converter_fn(builder, node, graph, err)
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_operators.py", line 522, in _convert_reshape
    "CoreML only supports Reshape layer when the target shape is static and known apriori")
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/onnx_coreml/_error_utils.py", line 75, in missing_initializer
    format(node.op_type, node.inputs[0], node.outputs[0], err_message, self.rerun_suggestion)
**ValueError: Missing initializer error in op of type Reshape, with input name = 586, output name = 596. Error message: CoreML only supports Reshape layer when the target shape is static and known apriori** 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.


Process finished with exit code 1

```
import sys
from onnx import onnx_pb
from onnx_coreml import convert

model_in = sys.argv[1]
model_out = sys.argv[2]

model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
coreml_model = convert(model_proto,
					   None,
                       image_input_names=['image'],
					   add_custom_layers=True,
					   minimum_ios_deployment_target='12'    # TypeError: 'set' object is not callable
                      )
coreml_model.save(model_out)
```

**Comment by dzyjjpy** [comment]
@bhushan23 @alexanderhudym @aseemw here is is my model, if you want to reproduce the issue:
https://drive.google.com/drive/folders/1lqH5-QjI0zx-iulScLONgVMTctJ6l0vA?usp=sharing

(if I use minimum_ios_deployment_target='13', can convert coreml successfully, but will have errors when compiling: 
**Custom layers have been added to the CoreML model corresponding to the following ops in the onnx model: 
1/1: op type: Upsample, op input names and shapes: [('551', 'Shape not available'), ('575', 'Shape not available')], op output names and shapes: [('576', 'Shape not available')])**
